######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 21 18:16:38 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dbmeter.h mainwindow.h
SOURCES += dbmeter.cpp main.cpp mainwindow.cpp
